services:
  app:
    build: .
    # Optional: name the image locally so compose won't try to pull a remote one
    image: au-powerball-stats-app:local
    container_name: au-powerball-stats
    ports:
      - "8080:8080"
    environment:
      TZ: "Australia/Adelaide"
      YEARS_START: "2018"
      DB_PATH: "/data/powerball.sqlite"
      UPDATE_CRON: "*/15 * * * *"
      PYTHONUNBUFFERED: "1"
      GUNICORN_CMD_ARGS: "--log-level info --access-logfile - --error-logfile -"
    volumes:
      # Run the *exact* code you just pulled from Git:
      - ./app:/srv/app:ro
      - ./data:/data
    restart: unless-stopped
